# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-handbook-of-quantitative-trading
title: 量潮量化交易手册
author: 量潮科技
description: 量潮量化交易手册
# Jupyter Book Config
only_build_toc_files: true
